build:
  image: node:8
  commands:
    - git submodule update --init
    - yarn run installAll
    - yarn test
    - yarn run eslint
    - yarn run checktype

compose:
  queue:
    image: rabbitmq:3
  database:
    image: redis:2.8
