build:
  image: node:4.3 
  commands:
    - git submodule update --init
    - npm run installAll
    - npm install .
    - npm test
    
compose:
  queue:
    image: rabbitmq:3
  database:
    image: redis:2.8
