language: node_js
node_js:
  - "10"
install:
  - git submodule update --init
  - yarn run installAll
script:
  - yarn test
  - yarn run eslint
  - yarn run checktype
cache:
  yarn: true
services:
  - redis
  - rabbitmq
